### ISSUE TITLE
Easy mechanism translation proposal

### ISSUE THREAD

**Issue by thepabloaguilar** [sobolevn/ship-it-boardgame#12]
Hi @sobolevn 👋🏽 

I'd to like to start the translation to PT-BR of the game but I want to do in way it's easy for future maintenance and new languages, so I have a proposal.

First we define some variables in a YAML file like this which is basically a translation table:
```yaml
general:
  first_player: Алисы
  second_player: Бориса
  hand: Рука
  table: Стол
  hidden_card: Закрытая карта
  reset: Сброс
  card:
    attack:
      name: Атака
      types:
        error: Ошибка
    component:
      name: Компонент
      types:
        internal_process: Бекенд
```

Then all the diagrams must use template tags to get the values (eg.: `{{ general.first_player }}`), we're going to render using Jinja and once we've done it we can render using [Drawio API](https://github.com/tomkludy/docker-drawio-renderer), finally we just save in the folder!

The render process can be done locally and we verify using the CI/CD if the process was executed or automate the repository to commit it self in the master branch after a merge.

WDYT?
